version: "3.9"
services:
  db:
    image: mongo
    container_name: db
    expose:
      - 27017
    volumes:
      - db-vol:/data/db
    networks:
      - app-net

  app:
    container_name: app
    depends_on:
      - db
    build:
      context: .
    image: app
    ports:
      - "8080:8080"
    networks:
      - app-net
    environment:
      ENV: ${ENV:-test}
      MONGO_URI: mongodb://db:27017
    entrypoint: [ "./protobuf-app", "-enable_proxy=true", "-http_addr=:8080", "-grpc_addr=:8090" ]
    privileged: false
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 15s
      retries: 3
      start_period: 20s
      timeout: 5s

volumes:
  db-vol:

networks:
  app-net:
