apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  namespace: backend
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: backend
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: backend
  labels:
    app: posts-db
    tier: database
    version: v1
spec:
  serviceName: mongodb-test
  replicas: 1
  selector:
    matchLabels:
      app: posts-db
      tier: database
      version: v1
  template:
    metadata:
      name: posts-db
      namespace: backend
      labels:
        app: posts-db
        tier: database
        version: v1
    spec:
      containers:
        - name: db
          image: mongo
          volumeMounts:
            - name: db-volume
              mountPath: "/data/db"
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: pvc

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: backend
  labels:
    app: posts-db
    tier: database
    version: v1
spec:
  clusterIP: None
  selector:
    app: posts-db
    tier: database
    version: v1
