name: Api with Protoco Buffer
on:
  push:
    branches:
      - main
jobs:
  compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-gp/@v3
        with:
          go-version: 1.17

      - name: Tests
        run: go test -v ./...