name: Api with Protoco Buffer
on:
  push:
    branches:
      - main
jobs:
  compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup go env
        run: |
          go env -w GO111MODULE=on

      - name: Set up Go
        uses: actions/setup-go/@v3
        with:
          go-version: 1.17

      - name: Dependencies
        run: |
          make dependencies

      - name: Generate proto docs
        run: |
          buf generate

      - name: Tests
        run: |
          go test -v -coverprofile=coverage.out ./... | tee test.out
          cat test.out | go-junit-report > ./report.xml
          gocov convert coverage.out | gocov-xml > ./coverage-report.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./report.xml,./coverage-report.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
